### PR TITLE
Update Applist.java

### PR DESCRIPTION
**Pull request by away-l**
JSONObject info;
app_list.info.name   is app name 
app_list.info.img      is app-logo cache in storage--sdcard0 /  xxx.xxx.xxx/ some '.png'.

### CODE REVIEW

**Comment by away-l** [comment]
I am sorry. and i am sure it works great. please checking your android path AndroidManifest.xml add <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

At 2014-12-20 03:17:22, "jmrezayi2" <notifications@github.com> wrote:


Hello,

I am checking the changes. It does return the app list and the path for .png files, but does not create the directory and does not create png files there.

For example I get: "oovoo" and "/storage/emulated/0/com.ionicframework.xxx/Cache/com.oovoo.png" in the applist.info, but there is no folder created with path "/storage/emulated/0/com.ionicframework.xxx/" and consequently, no images are made.

I do fill this is a really good idea and needed. Do you have time to look into this and make sure it works? It would be great if you could.
I feel the mkdirs(path) does not work.

Thanks a lot!

**Comment by jmrezayi2** [comment]
Hi!

Yes, You can add it in the plugin xml so that when users add the plugin it gets added to the manifest by itself. I have already done this, so it works fine now.

Thanks a lot for your improvement! Really appreciate it!

**Comment by away-l** [comment]
Hi!
    and i must thanks for you.    Because of your "Applist"  plugin, now i work mostly in Plugin development. 
    think you.

**Comment by jmrezayi2** [comment]
Oh that is good news! This was my first plugin development experience.. I would like to hear more from you and would be happy to keep in touch. (I mostly do app development)

**Comment by away-l** [comment]
I am very happy to communicate with you.In the same way with you,I finished the application installed&&unstalled&&update automatically. 
I now work busy with  Payfor plugin with AliPay-SDK.

**Pull request merged**
